# basic site info: not subject to localization; localized site title and description are in about.yml
name: geetaasameekshaa
title: gītāsamīkṣā   
description: The Bhagavad Gita in the Bhishma Book of Sri Veda Vyasa's Mahabharata

theme: [] # disable default injected theme: we do all the styling ourselves

baseurl: ""   # site deployed to a domain/sub-domain

# default language: used to rewrite links for missing pages
# language codes are described in _data/languages.yml
# can't be used to define default frontmatter `lang`
default_lang: kan


# default frontmatter: each lang's content is in dir /lang as in /kan, /eng, /hin, ...
defaults:
  # defaults for all pages
  - scope:
      path: ""
      type: pages
    values:
      lang: kan                         # can't use default_lang config's value from above
      layout: default                   # default layout for all pages
      permalink: /:path/:basename.html  # one html per md in the dir where the md is

  # default value for `lang` key for pages in lang dirs: no need to include `lang` again in frontmatter
  # no need to specify anything for kan files because the only customization lang is already the default
  # add kan scope if a key other than `lang` needs a default value
  - scope:
      path: eng
    values:
      lang: eng

  - scope:
      path: hin
    values:
      lang: hin

  - scope:
      path: tam
    values:
      lang: tam

  - scope:
      path: tel
    values:
      lang: tel

  - scope:
      path: mal
    values:
      lang: mal


#files to exclude from Jekyll processing
exclude:
  - LICENSE.md      # expected only in root
  - README.md       # expected in root
  - "**/README.md"  # in any subdir: lang dirs may have own readme
  - "util"          # util contains useful scripts and such for site prep, etc.

#tell Jekyll it is OK to generate .nojekyll file 
#need the file in the generated site so that GH pages does not process generated site again
include: [".nojekyll"]
