# basic site info: not subject to localization
name: geetaasameekshaa
title: gītāsamīkṣā   #localized site title is maintained separately (see below)
description: The Bhagavad Gita in the Bhishma Book of Sri Veda Vyasa's Mahabharata

# language codes are defined and explained in _data/languages.yml

# localized site title: must do this because parts of GH Pages requires `title` by itself (see top of file)
localized_site_title:
  kan: ಗೀತಾಸಮೀಕ್ಷಾ
  eng: gītāsamīkṣā
  hin: गीतासमीक्षा
  tam: கீதாசமீக்ஷா
  tel: గీతాసమీక్షా
  mal: ഗീതാസമീക്ഷാ

# localized site description: must do this because parts of GH Pages has just one `description` per site
localized_site_description:
  kan: |
    ಶ್ರೀ ವೇದವ್ಯಾಸರು ರಚಿಸಿದ ಮಹಾಭಾರತದ ಭೀಷ್ಮಪರ್ವದಲ್ಲಿನ ಭಗವದ್ಗೀತಾ 
  eng: |
    The Bhagavad Gita in the Bhishma Book of Sri Veda Vyasa's Mahabharata
  hin: |
    श्री वेद व्यास द्वारा रचित महाभारत के भीष्म पर्व की भगवद् गीता
  tam: |
    ஸ்ரீ வேதவ்யாசர் எழுதிய மஹாபாரதத்தில் உள்ள பீஷ்ம பருவத்திலுள்ள பகவத் கீதா
  tel: |
    శ్రీ వేదవ్యాసుడు రచించిన మహాభారతంలోని భీష్మపర్వంలో ఉన్న భగవద్గీత
  mal: |
    ശ്രീ വേദവ്യാസൻ രചിച്ച മഹാഭാരതത്തിലെ ഭീഷ്മപർവത്തിൽ ഉൾപ്പെട്ട ഭാഗവദ് ഗീത


# default language: used to rewrite links for missing pages
# can't be used to define default frontmatter `lang`
default_lang: kan

# default frontmatter: each lang's content is in dir /lang as in /kan, /eng, /hin, ...
defaults:
  # defaults for all pages
  - scope:
      path: ""
      type: pages
    values:
      lang: kan # can't use default_lang config's value from above
      layout: "default" # default layout for all pages
      permalink: /:lang/:basename.html #one html per md

  # default value for `lang` key for pages in lang dirs: no need to include `lang` again in frontmatter
  # no need to specify anything for kan files because the only customization lang is already the default
  # add kan scope if a key other than `lang` needs a default value

  - scope:
      path: eng
    values:
      lang: eng

  - scope:
      path: hin
    values:
      lang: hin

  - scope:
      path: tam
    values:
      lang: tam

  - scope:
      path: tel
    values:
      lang: tel

  - scope:
      path: mal
    values:
      lang: mal


#files to exclude from Jekyll processing
exclude:
  - LICENSE.md        #expected only in root
  - "**/README.md"    #README.md anywere (lang dirs may have their own readme)
